package igu;

import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import logica.Practica1;

public class Pantalla extends javax.swing.JFrame {

    private BufferedImage imagenOriginal;
    private BufferedImage gris, rojo, verde, azul;
    private Practica1 logica = new Practica1();

    
    public Pantalla() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        verColor = new javax.swing.JButton();
        verGris = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnCargar = new javax.swing.JButton();
        aplicaContraste = new javax.swing.JButton();
        brilloSlider = new javax.swing.JSlider();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        contrasteSlider = new javax.swing.JSlider();
        aplicaBrillo = new javax.swing.JButton();
        colorSelect = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 0, 24)); // NOI18N
        jLabel1.setText("Procesamiento de Imágenes");

        jLabel2.setText("Acciones para hacerle a la imagen");

        verColor.setText("Ver RGB");
        verColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verColorActionPerformed(evt);
            }
        });

        verGris.setText("Ver Escala de Grises");
        verGris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verGrisActionPerformed(evt);
            }
        });

        jLabel3.setText("A color");

        jLabel4.setText("En escala de grises");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel5.setText("en formato .jpeg");

        btnCargar.setText("Cargar Imagen");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        aplicaContraste.setText("Aplicar Cambios");
        aplicaContraste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicaContrasteActionPerformed(evt);
            }
        });

        jLabel6.setText("Brillo");

        jLabel7.setText("Contaste");

        aplicaBrillo.setText("Aplicar Cambios");
        aplicaBrillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aplicaBrilloActionPerformed(evt);
            }
        });

        colorSelect.setText("Color");
        colorSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorSelectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(colorSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(verColor)
                                    .addComponent(verGris)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 124, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(aplicaContraste, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(aplicaBrillo, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(brilloSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contrasteSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(96, 96, 96)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(114, 114, 114)
                                        .addComponent(jLabel1))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnCargar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCargar)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(colorSelect))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(verColor)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(brilloSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(aplicaBrillo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(5, 5, 5)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verGris)
                    .addComponent(contrasteSlider, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aplicaContraste)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   // Mis botones
    
    private void verColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verColorActionPerformed
        if (imagenOriginal != null) {
            logica.mostrarImagen(escalarImagen(rojo, 800, 600), "Canal Rojo");
            logica.mostrarImagen(escalarImagen(verde, 800, 600), "Canal Verde");
            logica.mostrarImagen(escalarImagen(azul, 800, 600), "Canal Azul");
        } else {
            JOptionPane.showMessageDialog(this, "Primero carga una imagen");
        }
        
    }//GEN-LAST:event_verColorActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        JFileChooser selector = new JFileChooser();
        int res = selector.showOpenDialog(this);
        if (res == JFileChooser.APPROVE_OPTION) {
            try {
                File archivo = selector.getSelectedFile();
                imagenOriginal = ImageIO.read(archivo);
                // Crear canales y escala de grises
                rojo = logica.extraerCanalRojo(imagenOriginal);
                verde = logica.extraerCanalVerde(imagenOriginal);
                azul = logica.extraerCanalAzul(imagenOriginal);
                gris = logica.crearImagenGris(imagenOriginal);
                // Mostrar imagen original al subir la imagen
                logica.mostrarImagen(escalarImagen(imagenOriginal, 800, 600), "Imagen Original");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al cargar imagen: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_btnCargarActionPerformed

    private void verGrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verGrisActionPerformed
        if (gris != null) {
            logica.mostrarImagen(escalarImagen(gris, 800, 600), "Imagen en Escala de Grises");
        } else {
            JOptionPane.showMessageDialog(this, "Primero carga una imagen");
        }
        
    }//GEN-LAST:event_verGrisActionPerformed

    private void colorSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorSelectActionPerformed
        // check box del color
    }//GEN-LAST:event_colorSelectActionPerformed

    private void aplicaBrilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicaBrilloActionPerformed
        
        if (imagenOriginal != null) {
            int valor = brilloSlider.getValue();
            boolean enColor = colorSelect.isSelected();
            BufferedImage modificada = logica.ajustarBrillo(imagenOriginal, valor, enColor);
            logica.mostrarImagen(escalarImagen(modificada, 800, 600), "Imagen con Brillo");
        } else {
            JOptionPane.showMessageDialog(this, "Primero carga una imagen");
        }   
    }//GEN-LAST:event_aplicaBrilloActionPerformed

    private void aplicaContrasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicaContrasteActionPerformed

        if (imagenOriginal != null) {
            int valor = contrasteSlider.getValue();
            boolean enColor = colorSelect.isSelected();
            BufferedImage modificada = logica.ajustarContraste(imagenOriginal, valor, enColor);
            logica.mostrarImagen(escalarImagen(modificada, 800, 600), "Imagen con Contraste");
        } else {
            JOptionPane.showMessageDialog(this, "Primero carga una imagen");
        }
    }//GEN-LAST:event_aplicaContrasteActionPerformed
    
    private BufferedImage escalarImagen(BufferedImage imagen, int maxAncho, int maxAlto) {
        int ancho = imagen.getWidth();
        int alto = imagen.getHeight();
        double factor = Math.min((double) maxAncho / ancho, (double) maxAlto / alto);
        int nuevoAncho = (int) (ancho * factor);
        int nuevoAlto = (int) (alto * factor);

        Image temp = imagen.getScaledInstance(nuevoAncho, nuevoAlto, Image.SCALE_SMOOTH);
        BufferedImage escalada = new BufferedImage(nuevoAncho, nuevoAlto, BufferedImage.TYPE_INT_RGB);
        Graphics2D g2d = escalada.createGraphics();
        g2d.drawImage(temp, 0, 0, null);
        g2d.dispose();
        return escalada;
    }
   
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aplicaBrillo;
    private javax.swing.JButton aplicaContraste;
    private javax.swing.JSlider brilloSlider;
    private javax.swing.JButton btnCargar;
    private javax.swing.JCheckBox colorSelect;
    private javax.swing.JSlider contrasteSlider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton verColor;
    private javax.swing.JButton verGris;
    // End of variables declaration//GEN-END:variables

}
